# Target specific macros
TARGET = NXT

TARGET_CPP_SOURCES = nxt.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./nxt.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ${NXTOSEK}/ecrobot/ecrobot++.mak
